// Municipalities of Málaga province (mirror of src/lib/localitiesCatalog.ts).
//
// Duplicated on purpose: Deno edge functions cannot import through the Vite
// bundler aliases used by the frontend. Keep both lists in sync when the
// curated catalogue changes.

export const MALAGA_MUNICIPALITIES: readonly string[] = [
  "Málaga",
  "Torremolinos",
  "Benalmádena",
  "Fuengirola",
  "Mijas",
  "Marbella",
  "Estepona",
  "Manilva",
  "Casares",
  "Benahavís",
  "Ojén",
  "Istán",
  "Vélez-Málaga",
  "Rincón de la Victoria",
  "Nerja",
  "Torrox",
  "Frigiliana",
  "Cómpeta",
  "Algarrobo",
  "Sayalonga",
  "Periana",
  "Alcaucín",
  "Riogordo",
  "Colmenar",
  "Benamocarra",
  "Almáchar",
  "El Borge",
  "Comares",
  "Totalán",
  "Moclinejo",
  "Macharaviaya",
  "Iznate",
  "Canillas de Aceituno",
  "Canillas de Albaida",
  "Sedella",
  "Salares",
  "Árchez",
  "Alfarnate",
  "Alfarnatejo",
  "Arenas",
  "Benamargosa",
  "Cútar",
  "Viñuela",
  "Alhaurín de la Torre",
  "Almogía",
  "Alhaurín el Grande",
  "Coín",
  "Cártama",
  "Álora",
  "Pizarra",
  "Casarabonela",
  "Monda",
  "Guaro",
  "Tolox",
  "Alozaina",
  "Yunquera",
  "Antequera",
  "Archidona",
  "Campillos",
  "Teba",
  "Mollina",
  "Alameda",
  "Fuente de Piedra",
  "Humilladero",
  "Sierra de Yeguas",
  "Villanueva de la Concepción",
  "Villanueva del Trabuco",
  "Villanueva del Rosario",
  "Villanueva de Tapia",
  "Villanueva de Algaidas",
  "Casabermeja",
  "Cuevas Bajas",
  "Cuevas de San Marcos",
  "Valle de Abdalajís",
  "Ronda",
  "Arriate",
  "Benaoján",
  "Montejaque",
  "Jimera de Líbar",
  "Atajate",
  "Benadalid",
  "Benalauría",
  "Algatocín",
  "Jubrique",
  "Genalguacil",
  "Alpandeire",
  "Faraján",
  "Júzcar",
  "Pujerra",
  "Parauta",
  "Cartajima",
  "Igualeja",
  "Gaucín",
  "Cortes de la Frontera",
  "Benarrabá",
  "Montecorto",
  "Ardales",
  "El Burgo",
  "Cañete la Real",
  "Cuevas del Becerro",
  "Carratraca",
  "Almargen",
  "Serrato",
];
