
-- Disable placeholder / garbage locations
UPDATE public.locations
SET is_enabled = false
WHERE normalized_name IN (
  'city-name','city-name-1','city-name-2','city-name-3',
  'ciudad-1','ciudad-2','ciudad-desconocida','localidad',
  'not-specified','no-especificada','no-especificado','cruz'
);

-- Seed Málaga province municipalities (idempotent)
INSERT INTO public.locations (name, normalized_name, province, country, is_in_province_malaga, is_enabled)
VALUES
  ('Málaga','malaga','Málaga','ES',true,true),
  ('Marbella','marbella','Málaga','ES',true,true),
  ('Fuengirola','fuengirola','Málaga','ES',true,true),
  ('Torremolinos','torremolinos','Málaga','ES',true,true),
  ('Benalmádena','benalmadena','Málaga','ES',true,true),
  ('Estepona','estepona','Málaga','ES',true,true),
  ('Mijas','mijas','Málaga','ES',true,true),
  ('Vélez-Málaga','velez-malaga','Málaga','ES',true,true),
  ('Antequera','antequera','Málaga','ES',true,true),
  ('Ronda','ronda','Málaga','ES',true,true),
  ('Nerja','nerja','Málaga','ES',true,true),
  ('Alhaurín de la Torre','alhaurin-de-la-torre','Málaga','ES',true,true),
  ('Alhaurín el Grande','alhaurin-el-grande','Málaga','ES',true,true),
  ('Coín','coin','Málaga','ES',true,true),
  ('Rincón de la Victoria','rincon-de-la-victoria','Málaga','ES',true,true),
  ('Torrox','torrox','Málaga','ES',true,true),
  ('Álora','alora','Málaga','ES',true,true),
  ('Archidona','archidona','Málaga','ES',true,true),
  ('Cártama','cartama','Málaga','ES',true,true),
  ('Pizarra','pizarra','Málaga','ES',true,true),
  ('Campillos','campillos','Málaga','ES',true,true),
  ('Teba','teba','Málaga','ES',true,true),
  ('Mollina','mollina','Málaga','ES',true,true),
  ('Alameda','alameda','Málaga','ES',true,true),
  ('Casabermeja','casabermeja','Málaga','ES',true,true),
  ('Colmenar','colmenar','Málaga','ES',true,true),
  ('Periana','periana','Málaga','ES',true,true),
  ('Frigiliana','frigiliana','Málaga','ES',true,true),
  ('Cómpeta','competa','Málaga','ES',true,true),
  ('Algarrobo','algarrobo','Málaga','ES',true,true),
  ('Sayalonga','sayalonga','Málaga','ES',true,true),
  ('Benahavís','benahavis','Málaga','ES',true,true),
  ('Casares','casares','Málaga','ES',true,true),
  ('Manilva','manilva','Málaga','ES',true,true),
  ('Ojén','ojen','Málaga','ES',true,true),
  ('Istán','istan','Málaga','ES',true,true),
  ('Guaro','guaro','Málaga','ES',true,true),
  ('Tolox','tolox','Málaga','ES',true,true),
  ('Alozaina','alozaina','Málaga','ES',true,true),
  ('Yunquera','yunquera','Málaga','ES',true,true),
  ('Ardales','ardales','Málaga','ES',true,true),
  ('El Burgo','el-burgo','Málaga','ES',true,true),
  ('Gaucín','gaucin','Málaga','ES',true,true),
  ('Cortes de la Frontera','cortes-de-la-frontera','Málaga','ES',true,true),
  ('Almáchar','almachar','Málaga','ES',true,true),
  ('El Borge','el-borge','Málaga','ES',true,true),
  ('Comares','comares','Málaga','ES',true,true),
  ('Totalán','totalan','Málaga','ES',true,true),
  ('Moclinejo','moclinejo','Málaga','ES',true,true),
  ('Macharaviaya','macharaviaya','Málaga','ES',true,true),
  ('Iznate','iznate','Málaga','ES',true,true),
  ('Benamocarra','benamocarra','Málaga','ES',true,true),
  ('Canillas de Aceituno','canillas-de-aceituno','Málaga','ES',true,true),
  ('Canillas de Albaida','canillas-de-albaida','Málaga','ES',true,true),
  ('Sedella','sedella','Málaga','ES',true,true),
  ('Salares','salares','Málaga','ES',true,true),
  ('Árchez','archez','Málaga','ES',true,true),
  ('Alcaucín','alcaucin','Málaga','ES',true,true),
  ('Riogordo','riogordo','Málaga','ES',true,true),
  ('Alfarnate','alfarnate','Málaga','ES',true,true),
  ('Alfarnatejo','alfarnatejo','Málaga','ES',true,true),
  ('Villanueva del Trabuco','villanueva-del-trabuco','Málaga','ES',true,true),
  ('Villanueva del Rosario','villanueva-del-rosario','Málaga','ES',true,true),
  ('Villanueva de Tapia','villanueva-de-tapia','Málaga','ES',true,true),
  ('Villanueva de Algaidas','villanueva-de-algaidas','Málaga','ES',true,true),
  ('Villanueva de la Concepción','villanueva-de-la-concepcion','Málaga','ES',true,true),
  ('Sierra de Yeguas','sierra-de-yeguas','Málaga','ES',true,true),
  ('Humilladero','humilladero','Málaga','ES',true,true),
  ('Fuente de Piedra','fuente-de-piedra','Málaga','ES',true,true),
  ('Cañete la Real','canete-la-real','Málaga','ES',true,true),
  ('Cuevas del Becerro','cuevas-del-becerro','Málaga','ES',true,true),
  ('Arriate','arriate','Málaga','ES',true,true),
  ('Benaoján','benaojan','Málaga','ES',true,true),
  ('Montejaque','montejaque','Málaga','ES',true,true),
  ('Jimera de Líbar','jimera-de-libar','Málaga','ES',true,true),
  ('Atajate','atajate','Málaga','ES',true,true),
  ('Benadalid','benadalid','Málaga','ES',true,true),
  ('Benalauría','benalauria','Málaga','ES',true,true),
  ('Algatocín','algatocin','Málaga','ES',true,true),
  ('Jubrique','jubrique','Málaga','ES',true,true),
  ('Genalguacil','genalguacil','Málaga','ES',true,true),
  ('Alpandeire','alpandeire','Málaga','ES',true,true),
  ('Faraján','farajan','Málaga','ES',true,true),
  ('Júzcar','juzcar','Málaga','ES',true,true),
  ('Pujerra','pujerra','Málaga','ES',true,true),
  ('Parauta','parauta','Málaga','ES',true,true),
  ('Cartajima','cartajima','Málaga','ES',true,true),
  ('Igualeja','igualeja','Málaga','ES',true,true),
  ('Monda','monda','Málaga','ES',true,true),
  ('Casarabonela','casarabonela','Málaga','ES',true,true),
  ('Carratraca','carratraca','Málaga','ES',true,true)
ON CONFLICT DO NOTHING;

-- Re-enable Málaga province if accidentally disabled
UPDATE public.locations
SET is_enabled = true, is_in_province_malaga = true
WHERE normalized_name IN ('malaga','marbella','fuengirola','torremolinos','benalmadena','estepona','mijas','velez-malaga','antequera','ronda','nerja','coin','rincon-de-la-victoria','torrox','alhaurin-de-la-torre','alhaurin-el-grande');
